// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxrjWg2cA_FEP3WivRnno7eOLB16LAIF8',
    appId: '1:677843548509:web:d18504647e0ebaca5390b4',
    messagingSenderId: '677843548509',
    projectId: 'agri-connecte',
    authDomain: 'agri-connecte.firebaseapp.com',
    storageBucket: 'agri-connecte.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCid6ufLluq4hWd9xDvyWWGHARlgVd0Vu8',
    appId: '1:677843548509:android:78d992f67f57100b5390b4',
    messagingSenderId: '677843548509',
    projectId: 'agri-connecte',
    storageBucket: 'agri-connecte.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEG7D8GJIl1k9S4oO-GlYjfvteFKnMpZg',
    appId: '1:677843548509:ios:f610ed8a4816ae0a5390b4',
    messagingSenderId: '677843548509',
    projectId: 'agri-connecte',
    storageBucket: 'agri-connecte.firebasestorage.app',
    iosBundleId: 'com.example.agriMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEG7D8GJIl1k9S4oO-GlYjfvteFKnMpZg',
    appId: '1:677843548509:ios:f610ed8a4816ae0a5390b4',
    messagingSenderId: '677843548509',
    projectId: 'agri-connecte',
    storageBucket: 'agri-connecte.firebasestorage.app',
    iosBundleId: 'com.example.agriMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxrjWg2cA_FEP3WivRnno7eOLB16LAIF8',
    appId: '1:677843548509:web:97550a8ad4e4d8305390b4',
    messagingSenderId: '677843548509',
    projectId: 'agri-connecte',
    authDomain: 'agri-connecte.firebaseapp.com',
    storageBucket: 'agri-connecte.firebasestorage.app',
  );

}